CREATE TABLE IF NOT EXISTS rating_MPA (
                                          id INTEGER PRIMARY KEY,
                                          name varchar(5) NOT NULL
);

CREATE TABLE IF NOT EXISTS genres (
                                      id INTEGER PRIMARY KEY,
                                      name varchar(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
                                     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name varchar(100) NOT NULL,
                                     description varchar(200),
                                     releaseDate date,
                                     duration integer,
                                     rating_id integer REFERENCES rating_MPA (id),
                                     likes_counter integer default '0'
);

CREATE TABLE IF NOT EXISTS film_genres (
                                           film_id INTEGER REFERENCES films (id),
                                           genre_id INTEGER REFERENCES genres (id),
                                           CONSTRAINT pkFilmGenres PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS users (
                                     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     email varchar(100) NOT NULL,
                                     login varchar(50) NOT NULL,
                                     name varchar(100) NOT NULL,
                                     birthday date
);

CREATE TABLE IF NOT EXISTS friends (
                                       user_id INTEGER REFERENCES users (id),
                                       friend_id INTEGER REFERENCES users (id),
                                       friendship_status BOOLEAN,
                                       CONSTRAINT pkFriends PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS likes (
                                     film_id INTEGER REFERENCES films (id),
                                     user_id INTEGER REFERENCES users (id),
                                     CONSTRAINT pkLikes PRIMARY KEY (film_id, user_id)
);